// frontend/src/routes/search/Discussions.svelte
<script lang="ts">
  import ChevronDown from '~icons/heroicons/chevron-down';
  import ChatBubbleLeftRight from '~icons/heroicons/chat-bubble-left-right';
  import type { Webpage } from '$lib/api';

  export let discussions: Webpage[];

  let showMore = false;

  $: shownDiscussions = showMore ? discussions : discussions.slice(0, 4);
</script>

<div class="flex flex-col space-y-1.5 overflow-hidden">
  <div class="flex items-center space-x-1 text-lg">
    <ChatBubbleLeftRight class="text-sm" />
    <span>Discussions</span>
  </div>
  <div class="flex flex-col">
    {#each shownDiscussions as discussion}
      <div class="overflow-hidden">
        <div>
          <a class="text-sm" href={discussion.url}>
            {discussion.domain}
          </a>
        </div>
        <details class="group">
          <summary class="flex cursor-pointer list-none items-center space-x-2">
            <a
              class="text-md inline-block max-w-[calc(100%-10px)] truncate font-medium group-open:underline"
              title={discussion.title}
              href={discussion.url}
            >
              {discussion.title}
            </a>
            <ChevronDown class="text-sm transition group-open:rotate-180" />
          </summary>

          {#if discussion.snippet.type == 'normal'}
            <div class="mb-3 text-sm font-normal text-snippet">
              {#if typeof discussion.snippet.date == 'string'}
                <span class="text-gray-500">{discussion.snippet.date}</span>
              {/if}
              <span class="[&:nth-child(2)]:before:content-['—']">
                {@html discussion.snippet.text}
              </span>
            </div>
          {/if}
        </details>
      </div>
    {/each}
    <button
      class="noscript:hidden mt-3 w-fit rounded-full border px-2 py-1 hover:cursor-pointer hover:bg-neutral-100"
      on:click={() => (showMore = !showMore)}
    >
      {showMore ? 'Show less' : 'Show more'}
    </button>
  </div>
</div>

// frontend/islands/Discussions.tsx
import { match } from "ts-pattern";
import { HiChatBubbleLeftRightOutline } from "../icons/HiChatBubbleLeftRightOutline.tsx";
import { HiChevronDown } from "../icons/HiChevronDown.tsx";
import * as search from "../search/index.ts";
import { useState } from "preact/hooks";

export const Discussions = (
  { discussions }: { discussions: search.Webpage[] },
) => {
  const [showMore, setShowMore] = useState(false);

  const shownDiscussions = showMore ? discussions : discussions.slice(0, 4);

  return (
    <div class="flex flex-col space-y-1.5 overflow-hidden">
      <div class="flex space-x-1 text-lg">
        <HiChatBubbleLeftRightOutline class="w-4" />
        <span>Discussions</span>
      </div>
      <div class="flex flex-col">
        {shownDiscussions.map((discussion) => (
          <DiscussionItem discussion={discussion} />
        ))}
        <div
          class="mt-3 w-fit rounded-full border px-2 py-1 hover:cursor-pointer hover:bg-neutral-100"
          onClick={() => setShowMore((showMore) => !showMore)}
        >
          {showMore ? "Show less" : "Show more"}
        </div>
      </div>
    </div>
  );
};

const DiscussionItem = ({ discussion }: { discussion: search.Webpage }) => (
  <div class="overflow-hidden">
    <div>
      <a class="text-sm hover:no-underline" href={discussion.url}>
        {discussion.domain}
      </a>
    </div>
    <details class="group">
      <summary class="list-none flex cursor-pointer space-x-2">
        <a
          class="text-md truncate font-medium group-open:underline inline-block max-w-[calc(100%-10px)]"
          title={discussion.title}
          href={discussion.url}
        >
          {discussion.title}
        </a>
        <HiChevronDown class="w-4 transition group-open:rotate-180" />
      </summary>

      {match(discussion.snippet)
        .with(
          { type: "normal" },
          ({ date, text }) => (
            <div class="mb-3 text-sm font-normal text-snippet">
              {typeof date == "string" && (
                <span class="text-gray-500">{date}</span>
              )}
              <span
                class="[&:nth-child(2)]:before:content-['—']"
                dangerouslySetInnerHTML={{
                  __html: text,
                }}
              />
            </div>
          ),
        )
        .otherwise(() => null)}
    </details>
  </div>
);
