// frontend/components/Site.tsx
import { twMerge } from "tailwind-merge";
import { ComponentChildren } from "preact";

export const Site = (
  { href, right, children }: {
    href: string;
    right?: ComponentChildren;
    children?: ComponentChildren;
  },
) => (
  <span class="group bg-brand-500 transition rounded-lg flex dark:bg-brand-800 overflow-hidden">
    <a
      href={href}
      class={twMerge(`
        transition py-2
        text-white
        bg-brand-500 hover:bg-brand-600 active:bg-brand-700
        dark:bg-brand-800 dark:hover:bg-brand-700 dark:active:bg-brand-600
        ${right ? "pl-3 pr-2" : "px-3"}
      `)}
    >
      {children ?? href}
    </a>
    {right && (
      <>
        <span class="w-px bg-brand-100 my-2 dark:bg-brand-950 group-hover:bg-transparent transition" />
        {right}
      </>
    )}
  </span>
);

export const SiteWithDelete = (
  { href, children, onDelete }: {
    href: string;
    children?: ComponentChildren;
    onDelete: () => void;
  },
) => (
  <Site
    href={href}
    right={
      <button
        class={twMerge(`
          remove-site cursor-pointer px-2 text-sm transition
        text-white
        bg-brand-500 hover:bg-brand-600 active:bg-brand-700
          dark:bg-brand-800 dark:hover:bg-brand-700 dark:active:bg-brand-600
        `)}
        onClick={() => onDelete()}
      >
        ×
      </button>
    }
  >
    {children}
  </Site>
);

// frontend/src/lib/components/Site.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { twMerge } from 'tailwind-merge';

  export let href: string;

  const dispatch = createEventDispatcher<{ delete: null }>();
</script>

<span class="group flex overflow-hidden rounded-lg bg-brand-500 transition dark:bg-brand-800">
  <a
    {href}
    class={twMerge(
      'bg-brand-500 py-2',
      'text-white',
      'transition hover:bg-brand-600 active:bg-brand-700',
      'dark:bg-brand-800 dark:hover:bg-brand-700 dark:active:bg-brand-600',
      'pl-3 pr-2',
    )}
  >
    <slot />
  </a>
  <span class="my-2 w-px bg-brand-100 transition group-hover:bg-transparent dark:bg-brand-950" />
  <button
    class={twMerge(`
          remove-site cursor-pointer bg-brand-500 px-2 text-sm
        text-white
        transition hover:bg-brand-600 active:bg-brand-700
          dark:bg-brand-800 dark:hover:bg-brand-700 dark:active:bg-brand-600
        `)}
    on:click={() => dispatch('delete')}
  >
    ×
  </button>
</span>
